{
  "bio-core-mix": {
    "py3.8.12_onnx": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format onnx not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 120, in test_resource\n    with create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 185, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 116, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.8.12_pytorch_script": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format pytorch_script not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 120, in test_resource\n    with create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 185, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 116, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.8.12_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format pytorch_state_dict not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 120, in test_resource\n    with create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 185, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 116, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.8.12_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "module 'tensorflow._api.v2.saved_model' has no attribute 'tag_constants'",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 123, in test_resource\n    results = predict(prediction_pipeline, inputs)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction.py\", line 261, in predict\n    return prediction_pipeline.forward(*tagged_data)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 129, in forward\n    prediction = self.predict(*preprocessed)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 124, in predict\n    return self._model.forward(*input_tensors)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 59, in forward\n    return self._forward(*input_tensors)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\", line 98, in _forward\n    result = self._forward_tf(*data)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\", line 61, in _forward_tf\n    tag = tf.saved_model.tag_constants.SERVING\n"
        ]
      }
    ],
    "py3.9.7_onnx": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format onnx not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 120, in test_resource\n    with create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 185, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 116, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.9.7_pytorch_script": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format pytorch_script not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 120, in test_resource\n    with create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 185, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 116, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.9.7_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format pytorch_state_dict not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 120, in test_resource\n    with create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 185, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 116, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.9.7_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "module 'tensorflow._api.v2.saved_model' has no attribute 'tag_constants'",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 123, in test_resource\n    results = predict(prediction_pipeline, inputs)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction.py\", line 261, in predict\n    return prediction_pipeline.forward(*tagged_data)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 129, in forward\n    prediction = self.predict(*preprocessed)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 124, in predict\n    return self._model.forward(*input_tensors)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 59, in forward\n    return self._forward(*input_tensors)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\", line 98, in _forward\n    result = self._forward_tf(*data)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\", line 61, in _forward_tf\n    tag = tf.saved_model.tag_constants.SERVING\n"
        ]
      }
    ]
  }
}