error: No module named 'torch'
name: reproduced test outputs
traceback: ["  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/core/resource_tests.py\",
    line 96, in test_resource\n    rd = load_resource_description(\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/core/resource_io/io_.py\",
    line 51, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
    nodes_module=nodes)\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/core/resource_io/utils.py\",
    line 125, in resolve_raw_resource_description\n    rd = SourceNodeTransformer().transform(rd)\n",
  "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 53, in transform\n    return transformer(node)\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 68, in generic_transformer\n    return dataclasses.replace(node, **{name:
    self.transform(value) for name, value in iter_fields(node)})\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 68, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value)
    for name, value in iter_fields(node)})\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 53, in transform\n    return transformer(node)\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 62, in transform_dict\n    return {key: self.transform(value) for key, value
    in node.items()}\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 62, in <dictcomp>\n    return {key: self.transform(value) for key, value
    in node.items()}\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 53, in transform\n    return transformer(node)\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 68, in generic_transformer\n    return dataclasses.replace(node, **{name:
    self.transform(value) for name, value in iter_fields(node)})\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 68, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value)
    for name, value in iter_fields(node)})\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/spec/shared/utils/_node_transformer.py\",
    line 53, in transform\n    return transformer(node)\n", "  File \"/usr/share/miniconda/envs/10.5281zenodo.5764893/lib/python3.10/site-packages/bioimageio/core/resource_io/utils.py\",
    line 85, in transform_ResolvedImportableSourceFile\n    importlib_spec.loader.exec_module(dep)
    \ # type: ignore  # todo: possible to use \"loader.load_module\"?\n", '  File
    "<frozen importlib._bootstrap_external>", line 883, in exec_module

    ', '  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

    ', "  File \"/tmp/bioimageio_cache/https/zenodo.org/api/files/8137780b-871f-4d7e-b130-a63847ece4d8/unet.py\",
    line 1, in <module>\n    import torch\n"]
